export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS'
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS'
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT'
